import json
import re
from pathlib import Path


def sanitize_filename(name: str) -> str:
    """Convert title or filename into a valid feature filename."""
    return re.sub(r'[^a-zA-Z0-9_-]', '_', name.lower()).strip('_')


def export_test_cases_to_feature(json_file_path: Path, output_dir: Path = None) -> Path:
    """
    Reads a JSON test cases file generated by Gemini and exports it as a Cucumber .feature file.
    """
    if output_dir is None:
        output_dir = Path(__file__).resolve().parents[2] / "features"

    output_dir.mkdir(parents=True, exist_ok=True)

    with open(json_file_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Handle both list of test cases or dict wrapper
    test_cases = data if isinstance(data, list) else data.get("test_cases", [])
    
    base_name = json_file_path.stem.replace("_test_cases", "")
    feature_filename = f"{sanitize_filename(base_name)}.feature"
    feature_file_path = output_dir / feature_filename

    lines = []
    lines.append(f"Feature: AI Generated Tests for {base_name.replace('_', ' ').title()}")
    lines.append(f"  As an automated QA engineer")
    lines.append(f"  I want to execute AI-generated test scenarios")
    lines.append(f"  So that I ensure UI robustness and correctness\n")

    for tc in test_cases:
        tc_id = tc.get("id", "TC000")
        title = tc.get("title", "Untitled Test")
        priority = tc.get("priority", "Medium")
        category = tc.get("category", "Functional")
        
        sanitized_category = category.replace(" ", "-")
        lines.append(f"  @{tc_id} @{priority} @{sanitized_category}")
        lines.append(f"  Scenario: {title}")
        
        # Preconditions
        preconditions = tc.get("preconditions", [])
        if preconditions:
            for pre in preconditions:
                lines.append(f"    Given precondition: {pre}")
        else:
            lines.append(f"    Given I am on the target page")

        # Steps
        steps = tc.get("steps", [])
        for step in steps:
            action = step.get("action", "").lower()
            target = step.get("target", "")
            value = step.get("value", "")
            key = step.get("key", "")
            expected = step.get("expected", {})
            step_desc = step.get("step", "")

            # Map actions to BDD given/when/then
            if action in ["navigate"]:
                lines.append(f"    When I navigate to {value or target}")
            elif action in ["click"]:
                lines.append(f"    When I click on \"{target}\"")
            elif action in ["fill", "type"]:
                lines.append(f"    When I fill \"{target}\" with \"{value}\"")
            elif action in ["clear"]:
                lines.append(f"    When I clear \"{target}\"")
            elif action in ["press"]:
                lines.append(f"    When I press key \"{key or value}\" on \"{target}\"")
            elif action in ["focus"]:
                lines.append(f"    When I focus on \"{target}\"")
            elif action in ["wait"]:
                lines.append(f"    When I wait for {value or 2} seconds")
            elif action in ["verify"]:
                v_type = expected.get("type", "text")
                v_val = expected.get("value", "")
                lines.append(f"    Then I should verify {v_type} equals \"{v_val}\" on \"{target}\"")
            else:
                # Fallback step description
                lines.append(f"    When {step_desc}")

        lines.append("") # Blank line between scenarios

    feature_file_path.write_text("\n".join(lines), encoding="utf-8")
    print(f"[BDD Exporter] Exported feature file: {feature_file_path}")
    return feature_file_path
